import { motion } from "motion/react";
import { FileText, Eye, Video, Activity, Download, Calendar, ChevronDown, Plus, AlertCircle } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router";
import jsPDF from "jspdf";
import "jspdf-autotable";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { patientAPI } from "../../lib/api";
import { Skeleton } from "@mui/material";
import { useTranslation } from "../../lib/i18n";

interface TimelineRecord {
    id: string | number;
    type: string;
    title?: string;
    date: string;
    summary?: string;
    result?: string;
    details?: string;
    confidence?: string;
    hemoglobin_level?: string;
    prescription?: string;
    doctor_specialty?: string;
    status?: string;
    is_manual?: boolean;
}

export default function HealthTimelinePage() {
    const { t } = useTranslation();
    const navigate = useNavigate();
    const [expandedId, setExpandedId] = useState<string | number | null>(null);
    const [filterType, setFilterType] = useState<string>('all');
    const [isAddEventOpen, setIsAddEventOpen] = useState(false);
    const [newEvent, setNewEvent] = useState({ title: "", description: "", date: new Date().toISOString().split('T')[0] });
    const queryClient = useQueryClient();

    const { data: recordsData, isLoading, error } = useQuery({
        queryKey: ['patientTimeline', filterType],
        queryFn: () => patientAPI.getTimeline(filterType !== 'all' ? { event_type: filterType } : {}).then((res) => res.data)
    });

    const addEventMutation = useMutation({
        mutationFn: (data: { title: string; description: string; event_date: string; category: string }) => patientAPI.addTimelineEvent(data),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['patientTimeline'] });
            toast.success(t('patient.timeline.event_added', "Timeline event added successfully"));
            setIsAddEventOpen(false);
            setNewEvent({ title: "", description: "", date: new Date().toISOString().split('T')[0] });
        },
        onError: () => toast.error(t('patient.timeline.event_failed', "Failed to add event"))
    });

    const handleAddEvent = (e: React.FormEvent) => {
        e.preventDefault();
        addEventMutation.mutate({
            title: newEvent.title,
            description: newEvent.description,
            event_date: new Date(newEvent.date).toISOString(),
            category: "manual"
        });
    };

    const handleExportPDF = () => {
        if (!recordsData?.records?.length) {
            toast.error(t('patient.timeline.no_records_export', "No timeline records to export."));
            return;
        }
        const doc = new jsPDF();
        doc.setFontSize(20);
        doc.text(t('patient.timeline.title', "Health Timeline"), 14, 22);
        doc.setFontSize(11);
        doc.setTextColor(100);
        doc.text(t('patient.timeline.generated_by', "Generated by NetraAI (Healix)"), 14, 30);

        const tableColumn = [
            t('common.date', "Date"),
            t('common.type', "Type"),
            t('common.title', "Title"),
            t('common.summary', "Summary")
        ];
        const tableRows = recordsData.records.map((r: TimelineRecord) => [
            r.date,
            r.type,
            r.title,
            r.summary
        ]);

        interface JsPDFWithAutoTable extends jsPDF {
            autoTable: (options: Record<string, unknown>) => void;
        }
        (doc as unknown as JsPDFWithAutoTable).autoTable({
            startY: 40,
            head: [tableColumn],
            body: tableRows,
            theme: "grid",
            headStyles: { fillColor: [13, 148, 136] },
        });

        doc.save(`health_timeline_${new Date().toISOString().split("T")[0]}.pdf`);
        toast.success(t('patient.timeline.pdf_downloaded', "Timeline PDF Downloaded"));
    };

    if (isLoading) {
        return (
            <div className="min-h-screen pt-20 pb-12 px-6 bg-gradient-to-br from-[#F0FDFA] via-white to-[#F8FAFC]">
                <div className="max-w-3xl mx-auto space-y-8">
                    <div className="mb-8">
                        <Skeleton width={250} height={40} animation="wave" />
                        <Skeleton width={400} height={20} animation="wave" />
                    </div>
                    <div className="space-y-6">
                        {[1, 2, 3, 4].map(i => <Skeleton key={i} variant="rounded" height={100} animation="wave" className="rounded-2xl" />)}
                    </div>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-screen pt-20 px-6 flex flex-col items-center justify-center text-center bg-gray-50">
                <AlertCircle className="w-12 h-12 text-red-500 mb-4" />
                <h2 className="text-2xl font-bold text-[#0F172A] mb-2">{t('patient.timeline.unable_load', "Unable to load timeline")}</h2>
                <p className="text-[#64748B] max-w-md mb-6">{(error as Error).message}</p>
                <Button onClick={() => queryClient.invalidateQueries({ queryKey: ['patientTimeline'] })} className="bg-[#0D9488] hover:bg-[#0F766E] text-white">{t('common.try_again', "Try Again")}</Button>
            </div>
        );
    }

    const records: TimelineRecord[] = recordsData?.records || [];

    return (
        <div className="min-h-screen pt-20 pb-12 px-6 bg-gradient-to-br from-[#F0FDFA] via-white to-[#F8FAFC]">
            <div className="max-w-3xl mx-auto">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                        <h1 className="text-3xl font-bold text-[#0F172A] mb-2">{t('patient.timeline.title', "Health Timeline")}</h1>
                        <p className="text-[#64748B]">{t('patient.timeline.subtitle', "A chronological summary of your medical journey")}</p>
                    </motion.div>

                    <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="flex flex-wrap gap-2 justify-end">
                        <select
                            className="bg-white border border-gray-200 text-sm rounded-lg px-3 py-2 text-[#0F172A] shadow-sm outline-none focus:ring-2 focus:ring-[#0D9488]"
                            value={filterType}
                            onChange={(e) => setFilterType(e.target.value)}
                        >
                            <option value="all">{t('patient.timeline.filter_all', "All Events")}</option>
                            <option value="appointment">{t('patient.timeline.filter_consult', "Consultations")}</option>
                            <option value="scan">{t('patient.timeline.filter_scan', "AI Scans")}</option>
                            <option value="manual">{t('patient.timeline.filter_manual', "Manual Events")}</option>
                        </select>
                        <Button variant="outline" onClick={handleExportPDF} className="border-gray-200 text-[#0F172A] hover:bg-gray-50 bg-white">
                            <Download className="w-4 h-4 mr-2" /> {t('common.export', "Export")}
                        </Button>
                        <Dialog open={isAddEventOpen} onOpenChange={setIsAddEventOpen}>
                            <DialogTrigger asChild>
                                <Button className="bg-[#0D9488] hover:bg-[#0F766E] text-white shadow-md">
                                    <Plus className="w-4 h-4 mr-2" /> {t('patient.timeline.add_event', "Add Event")}
                                </Button>
                            </DialogTrigger>
                            <DialogContent className="sm:max-w-[425px]">
                                <DialogHeader>
                                    <DialogTitle>{t('patient.timeline.add_manual_event', "Add Manual Timeline Event")}</DialogTitle>
                                </DialogHeader>
                                <form onSubmit={handleAddEvent} className="space-y-4 pt-4">
                                    <div className="space-y-2">
                                        <Label htmlFor="title">{t('patient.timeline.event_title', "Event Title")}</Label>
                                        <Input
                                            id="title"
                                            value={newEvent.title}
                                            onChange={(e) => setNewEvent({ ...newEvent, title: e.target.value })}
                                            placeholder={t('patient.timeline.title_placeholder', "e.g., Started new medication")}
                                            required
                                        />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="date">{t('common.date', "Date")}</Label>
                                        <Input
                                            id="date"
                                            type="date"
                                            value={newEvent.date}
                                            onChange={(e) => setNewEvent({ ...newEvent, date: e.target.value })}
                                            required
                                        />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="description">{t('common.description', "Description")}</Label>
                                        <Textarea
                                            id="description"
                                            value={newEvent.description}
                                            onChange={(e) => setNewEvent({ ...newEvent, description: e.target.value })}
                                            placeholder={t('patient.timeline.desc_placeholder', "Provide more details about this event...")}
                                            rows={3}
                                            required
                                        />
                                    </div>
                                    <div className="flex justify-end gap-2 pt-2">
                                        <Button type="button" variant="outline" onClick={() => setIsAddEventOpen(false)}>
                                            {t('common.cancel', "Cancel")}
                                        </Button>
                                        <Button type="submit" disabled={addEventMutation.isPending} className="bg-[#0D9488] hover:bg-[#0F766E] text-white">
                                            {addEventMutation.isPending ? t('common.adding', "Adding...") : t('patient.timeline.add_event', "Add Event")}
                                        </Button>
                                    </div>
                                </form>
                            </DialogContent>
                        </Dialog>
                    </motion.div>
                </div>

                {/* Timeline */}
                <div className="relative">
                    {/* Vertical line */}
                    {records.length > 0 && (
                        <div className="absolute left-6 top-0 bottom-0 w-0.5 bg-gradient-to-b from-[#0D9488] via-[#0EA5E9] to-gray-200" />
                    )}

                    <div className="space-y-6">
                        {records.map((record, i) => {
                            const isScan = record.type === "AI Scan";
                            const isConsultation = record.type === "Consultation" || record.type === "Video Consultation" || record.type === "In-Person Consultation";
                            const isAnemic = (record.result || '').toLowerCase() === "anemic";
                            const isNormal = (record.result || '').toLowerCase() === "normal";

                            return (
                                <motion.div
                                    key={record.id || `evt-${i}`}
                                    initial={{ opacity: 0, x: -20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: 0.1 * i }}
                                    className="relative pl-16"
                                >
                                    {/* Timeline dot */}
                                    <div className={`absolute left-4 w-5 h-5 rounded-full border-4 border-white z-10 ${isScan
                                        ? (isAnemic ? "bg-[#F43F5E]" : (isNormal ? "bg-[#22C55E]" : "bg-[#F59E0B]"))
                                        : isConsultation ? "bg-[#0EA5E9]" : "bg-[#8B5CF6]"
                                        }`} />

                                    <Card className="border border-gray-100 overflow-hidden hover:shadow-md transition-shadow bg-white">
                                        <div
                                            className="p-5 cursor-pointer hover:bg-gray-50/50 transition-colors"
                                            onClick={() => setExpandedId(expandedId === record.id ? null : record.id)}
                                        >
                                            <div className="flex items-start md:items-center justify-between flex-col md:flex-row gap-4">
                                                <div className="flex items-center gap-3 w-full">
                                                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${isScan ? "bg-[#0D9488]/10" : isConsultation ? "bg-[#0EA5E9]/10" : "bg-[#8B5CF6]/10"
                                                        }`}>
                                                        {isScan ? (
                                                            <Eye className="w-5 h-5 text-[#0D9488]" />
                                                        ) : isConsultation ? (
                                                            <Video className="w-5 h-5 text-[#0EA5E9]" />
                                                        ) : (
                                                            <Activity className="w-5 h-5 text-[#8B5CF6]" />
                                                        )}
                                                    </div>
                                                    <div className="flex-1">
                                                        <h3 className="font-semibold text-[#0F172A]">{record.title || record.type}</h3>
                                                        <div className="flex flex-wrap items-center gap-2 text-sm text-[#64748B] mt-1">
                                                            <span className="flex items-center gap-1 bg-gray-100 px-2 py-0.5 rounded-md"><Calendar className="w-3 h-3" /> {record.date}</span>
                                                            <span className="bg-gray-100 px-2 py-0.5 rounded-md">{record.type}</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="flex items-center justify-between w-full md:w-auto md:justify-end gap-3 px-1 md:px-0">
                                                    {isScan && (
                                                        <span className={`text-sm font-semibold px-3 py-1 rounded-full capitalize ${isAnemic ? "bg-[#F43F5E]/10 text-[#F43F5E]" :
                                                            isNormal ? "bg-[#22C55E]/10 text-[#22C55E]" :
                                                                "bg-[#F59E0B]/10 text-[#F59E0B]"
                                                            }`}>{t(`models.prediction.${(record.result || record.summary || '').toLowerCase()}`, record.result || record.summary)}</span>
                                                    )}
                                                    {isConsultation && (
                                                        <span className={`text-sm font-semibold px-3 py-1 rounded-full capitalize ${record.status === 'completed' ? 'bg-[#22C55E]/10 text-[#22C55E]' :
                                                            record.status === 'cancelled' ? 'bg-red-100 text-red-600' : 'bg-blue-100 text-blue-600'
                                                            }`}>{t(`common.status_${(record.status || '').toLowerCase()}`, record.status)}</span>
                                                    )}
                                                    <ChevronDown className={`w-4 h-4 text-gray-400 transition-transform ${expandedId === record.id ? "rotate-180" : ""}`} />
                                                </div>
                                            </div>
                                        </div>

                                        {expandedId === record.id && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: "auto", opacity: 1 }}
                                                className="border-t border-gray-100 p-5 bg-gray-50"
                                            >
                                                {isScan ? (
                                                    <div>
                                                        <p className="text-sm text-[#0F172A] mb-3 leading-relaxed">{record.details}</p>
                                                        <div className="flex items-center gap-4">
                                                            <div>
                                                                <p className="text-xs text-[#64748B] uppercase font-bold">{t('patient.timeline.ai_confidence', "AI Confidence")}</p>
                                                                <p className="text-sm font-semibold text-[#0D9488]">{record.confidence}</p>
                                                            </div>
                                                            {record.hemoglobin_level && (
                                                                <div>
                                                                    <p className="text-xs text-[#64748B] uppercase font-bold">{t('patient.timeline.est_hb', "Estimated Hb")}</p>
                                                                    <p className="text-sm font-semibold text-[#0F172A]">{record.hemoglobin_level} g/dL</p>
                                                                </div>
                                                            )}
                                                        </div>
                                                    </div>
                                                ) : isConsultation ? (
                                                    <div className="space-y-4">
                                                        <div>
                                                            <p className="text-xs font-bold text-[#64748B] uppercase mb-1">{t('patient.timeline.consult_summary', "Consultation Summary")}</p>
                                                            <p className="text-sm text-[#0F172A] leading-relaxed">{record.summary}</p>
                                                        </div>
                                                        {record.prescription && (
                                                            <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
                                                                <p className="text-xs font-bold text-[#64748B] uppercase mb-2 flex items-center gap-1">
                                                                    <FileText className="w-3 h-3" /> {t('patient.timeline.digital_prescription', "Digital Prescription")}
                                                                </p>
                                                                <p className="text-sm text-[#0F172A] whitespace-pre-line">{record.prescription}</p>
                                                            </div>
                                                        )}
                                                        <div className="flex items-center gap-2 text-sm text-[#64748B]">
                                                            <span className="font-semibold text-[#0F172A]">{record.doctor_specialty}</span>
                                                        </div>
                                                    </div>
                                                ) : (
                                                    <div className="space-y-4">
                                                        <div>
                                                            <p className="text-xs font-bold text-[#64748B] uppercase mb-1">{t('patient.timeline.event_description', "Event Description")}</p>
                                                            <p className="text-sm text-[#0F172A] leading-relaxed">{record.summary}</p>
                                                        </div>
                                                    </div>
                                                )}
                                                <div className="flex flex-wrap gap-2 mt-6">
                                                    <Button variant="outline" size="sm" className="h-9 px-4 border-gray-200 hover:bg-white hover:text-[#0D9488] hover:border-[#0D9488]">
                                                        <Download className="w-3.5 h-3.5 mr-2" /> {t('common.download_pdf', "Download PDF")}
                                                    </Button>
                                                </div>
                                            </motion.div>
                                        )}
                                    </Card>
                                </motion.div>
                            );
                        })}

                        {records.length === 0 && (
                            <Card className="p-12 text-center border-dashed border-2 bg-white/50 border-gray-200">
                                <Activity className="w-16 h-16 text-gray-200 mx-auto mb-4" />
                                <h3 className="text-lg font-bold text-[#0F172A] mb-1">{t('patient.timeline.no_events', "No timeline events")}</h3>
                                <p className="text-[#64748B] mb-6">{t('patient.timeline.no_events_desc', "Your health events, scans, and appointments will appear here.")}</p>
                                <Button onClick={() => navigate('/patient/scan')} className="bg-[#0D9488] hover:bg-[#0F766E] text-white">{t('patient.timeline.perform_scan', "Perform AI Scan")}</Button>
                            </Card>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
